### ISSUE TITLE
Works Great, fabulous even. but doesnt denoise the last 3 frames

### ISSUE THREAD

**Issue by kenw-github** [DrachenSeele/SuperImageDenoiser#18]
Hi. I`m using blender 3.6 and for some reason it doesn`t render the last 3 frames.
OpenEXR and preview folder renders all 70 frames, but denoise folder only renders 67 frames.

Am using SID Temporal, Super Quality, Volumetric(All), PNG, 0 overscan, disabled motion blur.

Thanks

**Comment by kenw-github** [comment]
Ayo found the fix.

For those having problems, Here`s what the devs commented on Youtube

"Hi, make sure your frame range is set correctly. Try having your current frame be on the first frame of the animation.

Due to the way temporal denoising works. You will have fewer denoised frames than noisy frames. In the case of SID, 1 frame in the beginning and 2 frames in the end will not be denoised and cut off"

So it`s fixed by setting Frame start-1 and Frame End+2, in my case start 0 end 72.

great work man.

**Comment by DrachenSeele** [comment]
Hi,
we are aware of this, and this behavior is noted on our gumroad page.
It is normal behavior for temporal denoising to have frames in the beginning and in the end that are filled with artifacts.
Instead of having frames with artifacts, we have removed these frames instead.

After careful consideration, and lots of feedback, SID 5.0, which will be the next release, will have the missing frames replaced by denoised, but non temporal frames instead.
The first and the two last frames are cut off.

Due to blender 4.0 breaking nearly every node based addon completely, I decided to do a complete refactor of the entire addon for the release of blender 4.0.
